### ISSUE TITLE
initiating SSE closure from server side

### ISSUE THREAD

**Issue by farhanz** [hyper-prog/hasses#1]
Is there a way to signal closure of the SSE streaming via FIFO?

Scenario:
1. Client has opened SSE streaming
2. Backend process writes special value to FIFO
3. On seeing this special value, the hasses back end must:
                a. Set HTTP Connection: close
                b. close CliConn fd

**Comment by farhanz** [comment]
Is there an option to delete SSE connection?
Scenario:
1. Client has opened SSE streaming (GET /sse?subscribe=XXX&id=ABCD1234)
2. Client should be able to issue a delete on the existing streaming (DELETE /sse?id=ABCD1234)

**Comment by hyper-prog** [comment]
I think the server side closing of the connection is not the proper way of close an SSE connection.
Most client will reconnect when the connection lost/closed.
https://stackoverflow.com/questions/24564030/is-an-eventsource-sse-supposed-to-try-to-reconnect-indefinitely
Because of these the client could immediately reconnect and open a new connection after each FIFO close message. I think the proper way to close an SSE connection is to send a special message to the specified client(s) to close the SSE connection from client side by calling EventSource.close()
https://developer.mozilla.org/en-US/docs/Web/API/EventSource
